version: '3.1'

services:
    deluge:
        image: oblique/deluge
        restart: always
        networks:
            - web
        ports:
            - 8112:8112 # web ui
            - 58846:58846 # daemon
            - 59912:59912 # incoming
            - 59912:59912/udp # incoming
            - 59922:59922 # outgoing
            - 59922:59922/udp # outgoing
        volumes:
            - /mnt/data/docker/deluge:/config
            - /mnt/data/media:/data
        env_file:
            - ../common.env
            - user.env
        environment:
            INCOMING_PORT_RANGE: 59912-59912
            OUTGOING_PORT_RANGE: 59922-59922
            UPNP: 'false'
            NAT_PMP: 'false'
            UTPEX: 'false'
            LSD: 'false'
            DHT: 'false'
            UTP: 'false'
        labels:
            traefik.enable: true
            traefik.port: 8112
            traefik.frontend.rule: Host:d.mc.example.com
            traefik.frontend.auth.basic.usersFile: /run/secrets/htpasswd
            traefik.frontend.auth.basic.removeHeader: true
    nzbget:
        image: oblique/nzbget
        restart: always
        networks:
            - web
        ports:
            - 6789:6789
        volumes:
            - /mnt/data/docker/nzbget:/config
            - /mnt/data/media:/data
        env_file:
            - ../common.env
            - user.env
        labels:
            traefik.enable: true
            traefik.port: 6789
            traefik.frontend.rule: Host:n.mc.example.com
            # nzbget has its own basic auth
    plex:
        image: linuxserver/plex
        restart: always
        hostname: Plex
        networks:
            - web
        ports:
            - 32400:32400
            - 32469:32469
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        volumes:
            - /mnt/data/docker/plex:/config
            - /mnt/data/media:/data
        env_file:
            - ../common.env
            - user.env
        environment:
            VERSION: latest
        labels:
            traefik.enable: true
            traefik.port: 32400
            traefik.frontend.rule: Host:p.mc.example.com
    sonarr:
        image: linuxserver/sonarr
        restart: always
        networks:
            - web
        ports:
            - 8989:8989
        links:
            - nzbget
            - deluge
        volumes:
            - /mnt/data/docker/sonarr:/config
            - /mnt/data/media/series:/tv
            - /mnt/data/media/downloads/complete/nzb/Series:/downloads
        env_file:
            - ../common.env
            - user.env
        labels:
            traefik.enable: true
            traefik.port: 8989
            traefik.frontend.rule: Host:s.mc.example.com
            traefik.frontend.auth.basic.usersFile: /run/secrets/htpasswd
            traefik.frontend.auth.basic.removeHeader: true
    radarr:
        image: linuxserver/radarr
        restart: always
        networks:
            - web
        ports:
            - 7878:7878
        links:
            - nzbget
            - deluge
        volumes:
            - /mnt/data/docker/radarr:/config
            - /mnt/data/media/movies:/movies
            - /mnt/data/media/downloads/complete/nzb/Movies:/downloads
        env_file:
            - ../common.env
            - user.env
        labels:
            traefik.enable: true
            traefik.port: 7878
            traefik.frontend.rule: Host:r.mc.example.com
            traefik.frontend.auth.basic.usersFile: /run/secrets/htpasswd
            traefik.frontend.auth.basic.removeHeader: true

networks:
    web:
        external: true
