version: '3.1'

services:
    deluge:
        image: oblique/deluge
        ports:
            - 8112:8112 # web ui
            - 58846:58846 # daemon
            - 59912:59912 # incoming
            - 59912:59912/udp # incoming
            - 59922:59922 # outgoing
            - 59922:59922/udp # outgoing
        networks:
            - default
            - nginx-proxy_default
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mnt/data/docker/deluge:/config
            - /mnt/data/media:/data
        env_file:
            - user.env
        environment:
            INCOMING_PORT_RANGE: 59912-59912
            OUTGOING_PORT_RANGE: 59922-59922
            UPNP: 'false'
            NAT_PMP: 'false'
            UTPEX: 'false'
            LSD: 'false'
            DHT: 'false'
            UTP: 'false'
            CERT_CN: '*.mc.example.com'
            VIRTUAL_HOST: d.mc.example.com
            VIRTUAL_PORT: 8112
    nzbget:
        image: oblique/nzbget
        ports:
            - 6789:6789
        networks:
            - default
            - nginx-proxy_default
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mnt/data/docker/nzbget:/config
            - /mnt/data/media:/data
        env_file:
            - user.env
        environment:
            CERT_CN: '*.mc.example.com'
            VIRTUAL_HOST: n.mc.example.com
            VIRTUAL_PORT: 6789
    plex:
        image: oblique/plexpass
        hostname: Plex
        ports:
            - 32400:32400
            - 32469:32469
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        networks:
            - default
            - nginx-proxy_default
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mnt/data/docker/plex:/config
            - /mnt/data/media:/data
        env_file:
            - user.env
        environment:
            CERT_CN: '*.mc.example.com'
            VIRTUAL_HOST: p.mc.example.com
            VIRTUAL_PORT: 32400
    sonarr:
        image: oblique/sonarr
        ports:
            - 8989:8989
        networks:
            - default
            - nginx-proxy_default
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mnt/data/docker/sonarr:/config
            - /mnt/data/media:/data
        env_file:
            - user.env
        environment:
            CERT_CN: '*.mc.example.com'
            VIRTUAL_HOST: s.mc.example.com
            VIRTUAL_PORT: 8989
    radarr:
        image: oblique/radarr
        ports:
            - 7878:7878
        networks:
            - default
            - nginx-proxy_default
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mnt/data/docker/radarr:/config
            - /mnt/data/media:/data
        env_file:
            - user.env
        environment:
            CERT_CN: '*.mc.example.com'
            VIRTUAL_HOST: r.mc.example.com
            VIRTUAL_PORT: 7878

networks:
    nginx-proxy_default:
        external: true
