version: '3.1'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /root/docker/nginx-proxy/htpasswd:/etc/nginx/htpasswd:ro
            - certs:/etc/nginx/certs:ro
            - dhparam:/etc/nginx/dhparam
        environment:
            SSL_POLICY: Mozilla-Modern
            RELOAD_CERTS_CMD: docker-gen -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
    letsencrypt:
        image: oblique/letsencrypt-route53
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/certs
        environment:
            AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
            AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
        secrets:
            - aws_access_key_id
            - aws_secret_access_key

volumes:
    certs:
    dhparam:

secrets:
    aws_access_key_id:
        file: aws_access_key_id
    aws_secret_access_key:
        file: aws_secret_access_key
