version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        network_mode: bridge
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /root/docker/nginx-proxy/certs:/etc/nginx/certs:ro
            - /root/docker/nginx-proxy/htpasswd:/etc/nginx/htpasswd:ro
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        network_mode: bridge
        volumes_from:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /root/docker/nginx-proxy/certs:/etc/nginx/certs:rw
            - /root/docker/nginx-proxy/htpasswd:/etc/nginx/htpasswd:rw
