version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        network_mode: bridge
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /root/docker/letsencrypt-nsupdate/certs:/etc/nginx/certs:ro
            - /root/docker/nginx-proxy/htpasswd:/etc/nginx/htpasswd:ro
    letsencrypt:
        image: oblique/letsencrypt-nsupdate
        network_mode: bridge
        volumes:
            - /root/docker/letsencrypt-nsupdate:/config
        environment:
            KEY_PATH: ${NSUPDATE_KEY_PATH}
            DNSSERVER: ${DNSSERVER}
            ZONE: ${ZONE}
            CONTACT_EMAIL: ${LETSENCRYPT_EMAIL}
